# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: provision-eddysanoli

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true
  tasks:
    # ---------------------------------------------- #
    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: yes

    # ---------------------------------------------- #
    - name: Install Git
      apt:
        name:
          - git
        state: latest

    # ---------------------------------------------- #
    - name: Install NVM and Put the Executable in "~/.nvm"
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "~/.nvm/nvm.sh"

    - name: Setup .profile (Add NVM to PATH)
      lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh
        create: yes

    - name: Install Node Versions
      shell: ". /root/.bashrc && nvm install {{item}}"
      with_items:
        - "v16.18.0"
        - "--lts"
        - "node"

    # ---------------------------------------------- #
    # Installing Docker consists of a multi-step process. Check here for more info:
    # https://www.ansiblepilot.com/articles/install-docker-in-debian-like-systems-ansible-module-apt_key-apt_repository-and-apt/

    - name: Install Docker Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: yes

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        update_cache: true
        state: latest

    # -------------------------------------------- #
    # Note: Use the HTTPS URL for the Git Repo in order to avoid the use of SSH Keys
    # Also use the "force" option to discard any local changes to the repo.
    - name: Clone the "Eddysanoli.com" Repo
      git:
        repo: https://github.com/eddysanoli/eddysanoli.com.git
        dest: /opt/eddysanoli_repo
        force: yes

    # -------------------------------------------- #
    - name: Clone the "Discord Automation Bot" Repo
      git:
        repo: https://github.com/eddysanoli/Discord-Automation-Bot.git
        dest: /opt/discord_bot
        force: yes

    # -------------------------------------------- #
    - name: Copy Files for Docker Compose Deployment
      copy:
        src: "/opt/ansible/storage/"
        dest: "/opt/storage/"
        directory_mode: yes

    - name: Take Down the Previous Docker Compose Stack and Volumes
      docker_compose:
        project_src: /opt/storage/docker
        remove_volumes: yes
        state: absent

    - name: Start Docker Compose Stack
      docker_compose:
        project_src: /opt/storage/docker
        state: present
