# Target all hosts in the inventory
- hosts: "*"

  # Name of the playbook
  name: provision-eddysanoli

  # Make it so that Ansible can "escalate" to root
  # (i.e. run commands using sudo)
  become: true
  tasks:
    # ---------------------------------------------- #
    - name: Update Server Packages
      apt:
        update_cache: yes
        upgrade: yes

    # ---------------------------------------------- #
    - name: Install Git and Docker
      apt:
        name:
          - git
        state: latest

    # ---------------------------------------------- #
    # Installing Docker consists of a multi-step process. Check here for more info:
    # https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04

    - name: Install Docker Dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: yes

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        update_cache: true
        state: latest
